name: Deploy Azure Infrastructure

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the Environment to deploy"
        required: true
        type: choice
        options:
          - dev
          - prod
jobs:
  Deploy_Azure_Infrastructure:
    runs-on: [ infra-iac ] # comments by NCK - need to use the selfhosted runner label
    steps:
      - name: checkout the code
        uses: actions/checkout@v3
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.0.0"
      - name: Configure Azure Credentials
        uses: azure/setup-azure-cli@v1
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init

      - name: Create or Select Terraform Workspace for individual workflows
        run: |
          terraform workspace select ${{ github.event.inputs.environment }} || terraform workspace new ${{ github.event.inputs.environment }}

      - name: Terraform Plan to test the changes
        run: |
          terraform plan -var-file="${{ github.event.inputs.environment }}.tfvars"

      - name: Terraform Apply
        if: success()
        run: |
          terraform apply -auto-approve -var-file="${{ github.event.inputs.environment }}.tfvars"